language: php

php: 
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - sudo find . -type d -exec chmod 777 {} +

script: phpunit